# Generated by Django 5.2.1 on 2025-06-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_userprofile_agent_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='organization',
            new_name='organisation',
        ),
    ]
